export default {
  GET_SYSTEMINFO: 'GET_SYSTEMINFO',
  GET_AUDIOMANAGER: 'GET_AUDIOMANAGER',
  GET_TOPBARHEIGHT: 'GET_TOPBARHEIGHT',
  SET_SONGID: 'SET_SONGID',
  SET_USERINFO: 'SET_USERINFO',
  SET_LOGINSTATE: 'SET_LOGINSTATE'
}
